version: '3'

services:
  db:
    image: postgres:9.4
    container_name: coss_db
  memcached:
    container_name: coss_memcache
    image: memcached
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    links:
      - db
      - memcached
    command: ./bin/run-dev.sh
