version: '3'

services:
  db:
    image: postgres:9.4
    container_name: coss_db
    environment:
      - POSTGRES_USER=coss_user
      - POSTGRES_PASSWORD=coss_password
      - POSTGRES_DB=coss_db
  memcached:
    image: memcached
    container_name: coss_memcache
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    links:
      - db
      - memcached
    command: ./bin/run-dev.sh
